version: '2'

services: 
  kafka-compose:
    image: lensesio/fast-data-dev:2.2.1
    environment: 
      ZK_PORT: 2181         # zookeeper
      BROKER_PORT: 9092     # kafka-broker
      REGISTRY_PORT: 8081   # schema-regitry
      REST_PORT: 8082       # kafka-rest-proxy
      CONNECT_PORT: 8083    # kafka-connect
      WEB_PORT: 3030        # fast-data-dev
    ports: 
      - 2181:2181
      - 9092:9092
      - 8081:8081
      - 8082:8082
      - 8083:8083
      - 3030:3030
  clickhouse-server:
    image: yandex/clickhouse-server
    ports: 
      - 8123:8123  # http interface
      - 9000:9000  # native client
    volumes: 
      - ./clickhouse/data:/var/lib/clickhouse
  grafana:
    image: grafana/grafana
    ports: 
     - 3000:3000   # web port
  superset: 
    image: apache/superset
    ports:
      - 8080:8080