version: '2'
services:
  zookeeper:
    image: debezium/zookeeper:${DEBEZIUM_VERSION}
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka:
    image: debezium/kafka:${DEBEZIUM_VERSION}
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181
  mysql:
    image: debezium/example-mysql:${DEBEZIUM_VERSION}
    ports:
      - 3306:3306
    environment:
      - MYSQL_ROOT_PASSWORD=debezium
      - MYSQL_USER=mysqluser
      - MYSQL_PASSWORD=mysqlpw
  clickhouse-server:
    image: yandex/clickhouse-server
    ports:
      - 8123:8123  # http interface
      - 9000:9000  # native client
  connect:
    build:
      context: debezium-jdbc-es
      dockerfile: Dockerfile
    ports:
      - 8083:8083
      - 5005:5005
    links:
      - kafka
      - mysql
      - clickhouse-server
    environment:
      - BOOTSTRAP_SERVERS=kafka:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  kafka-connect-ui:
    image: landoop/kafka-connect-ui
    ports:
      - 19003:8000
    environment:
      - CONNECT_URL=http://connect:8083
