version: '2'

services:
  zookeeper:
    image: holmofy/zookeeper:1.0
    build:
      context: ./zookeeper
      dockerfile: Dockerfile
    ports:
      - 2181:2181
      - 2888:2888
      - 3888:3888
  kafka-broker:
    image: holmofy/kafka:1.0
    build:
      context: ./kafka
      dockerfile: Dockerfile
    ports:
      - 9092:9092
    links:
      - zookeeper
    environment:
      - ZOOKEEPER_CONNECT=zookeeper:2181

  connect:
    image: holmofy/kafka-connect:1.31
    build:
      context: ./connect/debezium-connect-docker
      dockerfile: Dockerfile
    ports:
      - 8083:8083   # rest api
      - 5005:5005
    links:
      - kafka-broker
      - mysql-server
    environment:
      - BOOTSTRAP_SERVERS=kafka-broker:9092
      - GROUP_ID=1
      - CONFIG_STORAGE_TOPIC=my_connect_configs
      - OFFSET_STORAGE_TOPIC=my_connect_offsets
      - STATUS_STORAGE_TOPIC=my_source_connect_statuses

  # https://docs.confluent.io/platform/current/schema-registry/index.html
  kafka-schema-registry:
    image: confluentinc/cp-schema-registry:5.5.1
    ports:
      - 8081:8081
    links:
      - zookeeper
      - kafka-broker
    environment:
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: PLAINTEXT://kafka-broker:9092
      SCHEMA_REGISTRY_HOST_NAME: kafka-schema-registry
      SCHEMA_REGISTRY_LISTENERS: http://0.0.0.0:8081
