version: "3"

services:
  zoo1:
    image: zookeeper:3.4.9
    ports:
      - 2181:2181
    environment:
      ZOO_MY_ID: 1
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo2:
    image: zookeeper:3.4.9
    ports:
      - 2182:2181
    environment:
      ZOO_MY_ID: 2
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888
  zoo3:
    image: zookeeper:3.4.9
    ports:
      - 2183:2181
    environment:
      ZOO_MY_ID: 3
      ZOO_PORT: 2181
      ZOO_SERVERS: server.1=zoo1:2888:3888 server.2=zoo2:2888:3888 server.3=zoo3:2888:3888

  dubbo-admin:
    image: apache/dubbo-admin
    depends_on:
      - zoo1
      - zoo2
      - zoo3
    ports:
      - 8080:8080
    environment:
      - admin.registry.address=zookeeper://zoo1:2181,zookeeper://zoo2:2181,zookeeper://zoo3:2181
      - admin.config-center=zookeeper://zoo1:2181,zookeeper://zoo2:2181,zookeeper://zoo3:2181
      - admin.metadata-report.address=zookeeper://zoo1:2181,zookeeper://zoo2:2181,zookeeper://zoo3:2181